export const venues = {
  'xs-nightclub': {
    name: 'XS Nightclub',
    hotel: 'Encore at Wynn Las Vegas',
    address: '3121 S Las Vegas Blvd, Las Vegas, NV 89109',
    category: 'Nightclub',
    size: '40,000 sq ft',
    capacity: '~3,500',
    openDays: 'Friday, Saturday, Monday (select nights)',
    hours: '10:30 PM – 4:00 AM',
    tableMin: '$1,000–$3,000+ (weekend)',
    coverCharge: '$30–$50 general admission',
    music: 'EDM, House, Top 40',
    dresscode: 'Upscale — dress shoes, dark jeans or slacks required for men',
    image: 'https://images.unsplash.com/photo-1574391884720-bbc3740c59d1?w=800&q=80',
    description: 'XS Nightclub at Encore at Wynn Las Vegas is consistently rated one of the top nightclubs in the world. Its stunning combination of indoor and outdoor space — centered around a luminous outdoor pool area — creates an experience unlike any other venue in Las Vegas.',
    highlights: ['Outdoor pool area lit with thousands of lights', 'World-class DJ residencies year-round', 'Multiple bar areas indoor and outdoor', 'Premium Wynn service standards', 'Celebrity sightings every weekend'],
    slug: 'xs-nightclub',
  },
  'hakkasan-nightclub': {
    name: 'Hakkasan Nightclub',
    hotel: 'MGM Grand',
    address: '3799 S Las Vegas Blvd, Las Vegas, NV 89109',
    category: 'Nightclub',
    size: '80,000 sq ft',
    capacity: '~7,500',
    openDays: 'Thursday–Sunday',
    hours: '10:00 PM – 4:00 AM',
    tableMin: '$800–$2,500+ (weekend)',
    coverCharge: '$25–$40 general admission',
    music: 'EDM, House, Hip-hop (varies by room)',
    dresscode: 'Upscale — no athletic sneakers, shorts, or caps',
    image: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=800&q=80',
    description: 'Hakkasan at MGM Grand is the largest nightclub in Las Vegas, spanning six unique rooms across 80,000 square feet. From the intimate Ling Ling Lounge to the massive main floor, Hakkasan offers a complete nightlife experience under one roof.',
    highlights: ['Six distinct rooms and atmospheres', 'Multi-level layout with mezzanine and main floor', 'Intimate Ling Ling Club for smaller groups', 'World-renowned DJ residencies', 'Best venue for large groups in Vegas'],
    slug: 'hakkasan-nightclub',
  },
  'omnia-nightclub': {
    name: 'Omnia Nightclub',
    hotel: 'Caesars Palace',
    address: '3570 S Las Vegas Blvd, Las Vegas, NV 89109',
    category: 'Nightclub',
    size: '75,000 sq ft',
    capacity: '~3,000',
    openDays: 'Thursday–Sunday',
    hours: '10:30 PM – 4:00 AM',
    tableMin: '$900–$2,500+ (weekend)',
    coverCharge: '$30–$50 general admission',
    music: 'EDM, House, Top 40',
    dresscode: 'Upscale — no athletic shoes, shorts, or caps',
    image: 'https://images.unsplash.com/photo-1519671482749-fd09be7ccebf?w=800&q=80',
    description: "Omnia Nightclub at Caesars Palace is home to one of the most spectacular production shows in Las Vegas. The venue's iconic kinetic chandelier descends and transforms throughout the night, creating a light show synchronized with the music that has to be seen to be believed.",
    highlights: ['Iconic kinetic LED chandelier centerpiece', 'Rooftop terrace with Strip views', 'Three-level layout with distinct areas', 'Best production show in Las Vegas nightlife', 'Heart nightclub for smaller gatherings'],
    slug: 'omnia-nightclub',
  },
  'marquee-nightclub': {
    name: 'Marquee Nightclub',
    hotel: 'The Cosmopolitan of Las Vegas',
    address: '3708 S Las Vegas Blvd, Las Vegas, NV 89109',
    category: 'Nightclub',
    size: '60,000 sq ft',
    capacity: '~3,000',
    openDays: 'Friday, Saturday, Sunday',
    hours: '10:30 PM – 4:00 AM',
    tableMin: '$800–$2,000+ (weekend)',
    coverCharge: '$25–$40 general admission',
    music: 'Hip-hop, EDM, Top 40',
    dresscode: 'Smart casual to upscale',
    image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=800&q=80',
    description: 'Marquee Nightclub at The Cosmopolitan of Las Vegas delivers some of the Strip\'s best hip-hop programming alongside EDM residencies. Its exclusive Boombox Room and rooftop bungalows make it one of the most versatile nightlife venues in the city.',
    highlights: ['Rooftop bungalows with private pool access', 'Boombox Room for hip-hop nights', 'Cosmopolitan\'s central Strip location', 'Strong weekly hip-hop programming', 'Connected to Marquee Dayclub for day-to-night'],
    slug: 'marquee-nightclub',
  },
  'encore-beach-club': {
    name: 'Encore Beach Club',
    hotel: 'Encore at Wynn Las Vegas',
    address: '3121 S Las Vegas Blvd, Las Vegas, NV 89109',
    category: 'Dayclub',
    size: '60,000 sq ft',
    capacity: '~4,000',
    openDays: 'Friday–Sunday (seasonal, May–September)',
    hours: '11:00 AM – 6:00 PM',
    tableMin: '$2,500+ (cabana), $500+ (daybed)',
    coverCharge: '$50–$80 general admission',
    music: 'EDM, House, Top 40',
    dresscode: 'Fashion swimwear — no cargo shorts, athletic wear',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    description: 'Encore Beach Club is the gold standard of Las Vegas dayclubs. Run by the Wynn group, EBC delivers the same impeccable service, premium sound system, and world-class DJ programming that defines the Wynn brand — in a stunning outdoor pool setting.',
    highlights: ['Private bungalows with personal pools', 'World-class DJ residencies poolside', 'Wynn-level service and quality', 'Multiple pool areas and cabana tiers', 'Connected to XS for night continuation'],
    slug: 'encore-beach-club',
  },
}
